name: citrus
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
    - nibabel
    - nilearn
    - numpy
    - matplotlib
    - scipy
    - pandas
    - seaborn
    - meshio
    - pyvista
